/**
 * StockSentinel Human Approval Gate Logic
 * Enforces the core non-negotiable rule:
 * NO trade order may proceed to Agent B without an explicit human command!
 */

const { EventEmitter } = require('events');
const memoryStore = require('../memory/store');

class ApprovalGateLogic extends EventEmitter {
  constructor() {
    super();
    // Cache of proposals waiting for human review
    this.pendingProposals = new Map();
  }

  /**
   * Register a new proposal generated by The Strategist
   */
  submitProposal(proposal) {
    const proposalId = proposal.id || `prop_${Date.now()}_${Math.floor(Math.random() * 1000)}`;
    const record = {
      ...proposal,
      id: proposalId,
      status: 'PENDING',
      createdAt: new Date().toISOString()
    };

    this.pendingProposals.set(proposalId, record);
    memoryStore.addProposal(record);

    // Quality gate: only send actionable HIGH/MEDIUM confidence BUY or SELL to Telegram.
    // LOW confidence and WATCH_ONLY proposals are logged but never pushed to the user's phone.
    const isActionable = ['buy', 'sell'].includes(record.action?.toLowerCase());
    const isHighQuality = ['high', 'medium'].includes(record.confidence?.toLowerCase());

    if (isActionable && isHighQuality) {
      console.log(`[ApprovalGate] Proposal queued for Telegram: ${record.ticker} ${record.action.toUpperCase()} (${record.confidence.toUpperCase()})`);
      this.emit('proposal_created', record);
    } else {
      console.log(`[ApprovalGate] Proposal suppressed (${record.action}/${record.confidence}) — not sending to Telegram: ${record.ticker}`);
    }

    return record;
  }

  /**
   * Human Approve Command
   */
  approveProposal(proposalId, userNotes = '') {
    const proposal = this.pendingProposals.get(proposalId) || memoryStore.getProposal(proposalId);
    if (!proposal) {
      throw new Error(`Proposal ${proposalId} not found`);
    }

    if (proposal.status !== 'PENDING') {
      return { success: false, message: `Proposal already resolved as ${proposal.status}` };
    }

    proposal.status = 'APPROVED';
    proposal.approvedAt = new Date().toISOString();
    proposal.notes = userNotes;

    this.pendingProposals.delete(proposalId);
    memoryStore.updateProposalStatus(proposalId, 'APPROVED', { notes: userNotes });

    console.log(`[ApprovalGate] ✅ PROPOSAL APPROVED BY USER: ${proposal.ticker} ${proposal.action.toUpperCase()}`);
    this.emit('proposal_approved', proposal);

    return {
      success: true,
      proposal,
      message: `Approved ${proposal.action.toUpperCase()} ${proposal.suggested_quantity} shares of ${proposal.ticker}`
    };
  }

  /**
   * Human Reject Command
   */
  rejectProposal(proposalId, reason = 'User declined trade') {
    const proposal = this.pendingProposals.get(proposalId) || memoryStore.getProposal(proposalId);
    if (!proposal) {
      throw new Error(`Proposal ${proposalId} not found`);
    }

    if (proposal.status !== 'PENDING') {
      return { success: false, message: `Proposal already resolved as ${proposal.status}` };
    }

    proposal.status = 'REJECTED';
    proposal.rejectedAt = new Date().toISOString();
    proposal.rejectionReason = reason;

    this.pendingProposals.delete(proposalId);
    memoryStore.updateProposalStatus(proposalId, 'REJECTED', { rejectionReason: reason });

    console.log(`[ApprovalGate] ❌ PROPOSAL REJECTED BY USER: ${proposal.ticker} (Reason: ${reason})`);
    this.emit('proposal_rejected', proposal);

    return {
      success: true,
      proposal,
      message: `Rejected proposal for ${proposal.ticker}. Recorded in memory.`
    };
  }

  /**
   * Human Modify Command (Adjust quantity or action before approval)
   */
  modifyAndApprove(proposalId, modifiedFields = {}) {
    const proposal = this.pendingProposals.get(proposalId) || memoryStore.getProposal(proposalId);
    if (!proposal) {
      throw new Error(`Proposal ${proposalId} not found`);
    }

    if (proposal.status !== 'PENDING') {
      return { success: false, message: `Proposal already resolved as ${proposal.status}` };
    }

    if (modifiedFields.quantity) {
      proposal.suggested_quantity = parseInt(modifiedFields.quantity, 10);
    }
    if (modifiedFields.action) {
      proposal.action = modifiedFields.action.toLowerCase();
    }

    proposal.status = 'MODIFIED';
    proposal.modifiedAt = new Date().toISOString();

    this.pendingProposals.delete(proposalId);
    memoryStore.updateProposalStatus(proposalId, 'MODIFIED', {
      suggested_quantity: proposal.suggested_quantity,
      action: proposal.action
    });

    console.log(`[ApprovalGate] ✏️ PROPOSAL MODIFIED & APPROVED: ${proposal.ticker} ${proposal.action.toUpperCase()} (${proposal.suggested_quantity} units)`);
    this.emit('proposal_approved', proposal);

    return {
      success: true,
      proposal,
      message: `Modified and approved: ${proposal.action.toUpperCase()} ${proposal.suggested_quantity} ${proposal.ticker}`
    };
  }

  getPendingList() {
    return Array.from(this.pendingProposals.values());
  }
}

module.exports = new ApprovalGateLogic();
